### ISSUE TITLE
Error on input - Twitter

### ISSUE THREAD

**Issue by minjualgae** [minjualgae/eunjibot#56]
https://i.gyazo.com/cefc0a1afce580e50c11901bc8fc20fa.png

input:
;twitter delete ig_name #channel_name

output:
"Stopped following:"

**Comment by jhakezebedee** [comment]
it should be ;twitter delete <indexes>
see ;twitter feeds for the indexes

example:
;twitter delete 1 12 4

also. try using ;help twitter

**Comment by minjualgae** [comment]
I checked that out, and it also returns a empty "Stopped following: __" when using ;twitter delete ig_name_not_in_feeds
